name: Try to install package using npm or usin yarn

on:
  push:

jobs:
  using-yarn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/checkout@v2
      - name: Add package using yarn
        run: |
          echo '"//npm.pkg.github.com/:_authToken" "${{ secrets.GPR_ACCESS_TOKEN }}"' >> .yarnrc
          echo '"//npm.pkg.github.com/:_header:Authorization" "token ${{ secrets.GPR_ACCESS_TOKEN }}"' >> .yarnrc
          rm package.json
          yarn add @wdesportes/test-publish-npm --verbose

  using-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/checkout@v2
      - name: Add package using npm
        run: |
          echo '//npm.pkg.github.com/:_authToken=${{ secrets.GPR_ACCESS_TOKEN }}' >> .npmrc
          rm package.json
          npm install @wdesportes/test-publish-npm
