name: Try to install package using npm or usin yarn

on:
  push:

jobs:
  using-yarn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/checkout@v2
      - name: Add package using yarn
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GPR_ACCESS_TOKEN }}
        run: |
          yarn add @wdesportes/test-publish-npm

  using-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/checkout@v2
      - name: Add package using npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GPR_ACCESS_TOKEN }}
        run: |
          npm install @wdesportes/test-publish-npm
