name: Try to install package using npm or usin yarn

on:
  push:

jobs:
  using-yarn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/checkout@v2
      - name: Add package using yarn
        run: |
          yarn config set //npm.pkg.github.com/:_authToken "${{ secrets.GPR_ACCESS_TOKEN }}"
          yarn global add @wdesportes/test-publish-npm

  using-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/checkout@v2
      - name: Add package using npm
        run: |
          npm config set //npm.pkg.github.com/:_authToken "${{ secrets.GPR_ACCESS_TOKEN }}"
          npm install -g @wdesportes/test-publish-npm
